name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    environment:
      name: 'Website'
      url: https://www.mongo-modeler.com
    runs-on: ubuntu-latest
    name: Deploy Mongo Modeler
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build
        run: node --run build

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_GLACIER_093E76303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'apps/web/dist'
          skip_app_build: true
          skip_api_build: true
